export class Constants {
  /**
   * Full screen width.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Full screen height.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Content height.
   */
  static readonly CONTENT_HEIGHT: number = 300;

  /**
   * Tab index0.
   */
  static readonly TAB_INDEX_ZERO: number = 0;

  /**
   * Tab index1.
   */
  static readonly TAB_INDEX_ONE: number = 1;

  /**
   * Tab index2.
   */
  static readonly TAB_INDEX_TWO: number = 2;

  /**
   * Image middle size.
   */
  static readonly IMAGE_SIZE_MIDDLE: number = 56;

  /**
   * Image offset.
   */
  static readonly IMAGE_OFFSET: number = -15;

  /**
   * Image tab size.
   */
  static readonly IMAGE_SIZE_TAB: number = 22;

  /**
   * Animation duration (millisecond).
   */
  static readonly ANIMATION_DURATION: number = 300;

  /**
   * Translate bottom.
   */
  static readonly TRANSLATE_BOTTOM: number = 40;

  /**
   * Icon offset.
   */
  static readonly ICON_OFFSET: number = -3;

  /**
   * List content height.
   */
  static readonly MENU_CONTENT_HEIGHT: string = '110%';

  /**
   * Side tab width.
   */
  static readonly MENU_SIDE_TAB_WIDTH: string = '27.8%';

  /**
   * Side contend width.
   */
  static readonly MENU_SIDE_CONTEND_WIDTH: string = '72.2%';
}